name: Generate Galaga Game

on:
  schedule:
    - cron: "0 0 * * *" # Corre todos os dias à meia-noite
  workflow_dispatch: # Permite correr manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-galaga-game
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Open Source Galaga Game Contribution
        uses: jstrieb/github-profile-galaga@master
        with:
          username: ${{ github.repository_owner }}

      - name: Push SVG to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generated Galaga game" || exit 0
          git push
